name: Publish to NuGet

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 🔹 Setup .NET SDK for .NET 8 & .NET 9 (No .NET 4.8)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            8.0
            9.0
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      # 🔹 Debug Repository Structure
      - name: Debug Repository Structure
        run: ls -lah

      # 🔹 Ensure README.md & logo.png are included in the package
      - name: Copy README.md and logo.png
        run: |
          mkdir -p FibPaymentSdk
          cp README.md FibPaymentSdk/README.md || echo "README.md already exists"
          cp logo.png FibPaymentSdk/logo.png || echo "logo.png already exists"

      # 🔹 Verify Files Exist Before Packaging
      - name: Verify Files Exist
        run: ls -lah FibPaymentSdk/ && cat FibPaymentSdk/README.md || echo "README.md NOT FOUND!"

      # 🔹 Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # 🔹 Build the Project
      - name: Build the Project
        run: dotnet build --configuration Release --no-restore

      # 🔹 Create NuGet Package (Multi-Targeting)
      - name: Create NuGet Package
        run: dotnet pack --configuration Release --no-build --output nupkgs

      # 🔹 Publish to NuGet
      - name: Publish to NuGet
        run: dotnet nuget push nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
