name: Publish to NuGet

on:
  push:
    branches:
      - main  # Runs when changes are pushed to `main`
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_API_KEY }}

      - name: Ensure README.md exists
        run: ls -lah && cat README.md  # Debugging step to verify file exists

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Project
        run: dotnet build --configuration Release --no-restore
      
      - name: Check if README.md exists
        run: ls -lah FibPaymentSdk/ && cat FibPaymentSdk/README.md


      - name: Create NuGet Package
        run: dotnet pack --configuration Release --no-build

      - name: Publish to NuGet
        run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
